- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - build-essential
      - vim
      - tmux
      - htop
      - tree
      - jq
      - unzip
      - zip
      - python3-pip
      - python3-venv
      - openjdk-17-jdk
      - docker.io
      - docker-compose-plugin
    state: present

- name: Install classic snaps
  snap:
    name:
      - pycharm-community
      - intellij-idea-community
      - sublime-text
    classic: yes
    state: present

- name: Install snaps
  snap:
    name:
      - whatsapp-electron
      - steam
      - discord
      - firefox
    classic: yes
    state: present